import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowRightStartOnRectangleIcon,
  ExclamationTriangleIcon,
  MegaphoneIcon,
  ArrowDownIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  Bars3Icon,
  BeakerIcon,
  BellAlertIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  Cog6ToothIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CursorArrowRaysIcon,
  DevicePhoneMobileIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  EyeIcon,
  GlobeAltIcon,
  HandRaisedIcon,
  HandThumbUpIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LockClosedIcon,
  MapPinIcon,
  MicrophoneIcon,
  NewspaperIcon,
  PhoneIcon,
  PlayIcon,
  PowerIcon,
  PresentationChartBarIcon,
  ShieldCheckIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SquaresPlusIcon,
  StarIcon,
  SunIcon,
  TicketIcon,
  TrophyIcon,
  TvIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UsersIcon,
  VideoCameraIcon,
  WifiIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import type { IconName } from '@/content/types'

export type IconComponent = typeof AcademicCapIcon

/** Every icon the content module can reference, by name. */
export const icons: Record<IconName, IconComponent> = {
  hospital: BuildingOffice2Icon,
  home: HomeIcon,
  heart: HeartIcon,
  devices: CpuChipIcon,
  bell: BellAlertIcon,
  book: BookOpenIcon,
  calendar: CalendarDaysIcon,
  bolt: BoltIcon,
  user: UserIcon,
  shield: ShieldCheckIcon,
  lightbulb: LightBulbIcon,
  video: VideoCameraIcon,
  chart: ChartBarIcon,
  signal: SignalIcon,
  wifi: WifiIcon,
  alert: ExclamationCircleIcon,
  clipboard: ClipboardDocumentCheckIcon,
  chat: ChatBubbleLeftRightIcon,
  refresh: ArrowPathIcon,
  'check-circle': CheckCircleIcon,
  check: CheckIcon,
  microphone: MicrophoneIcon,
  eye: EyeIcon,
  elevator: ArrowsUpDownIcon,
  breath: ArrowsRightLeftIcon,
  touch: HandRaisedIcon,
  automations: SparklesIcon,
  users: UsersIcon,
  tv: TvIcon,
  lock: LockClosedIcon,
  phone: PhoneIcon,
  'squares-plus': SquaresPlusIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-down': ArrowDownIcon,
  external: ArrowTopRightOnSquareIcon,
  'chevron-down': ChevronDownIcon,
  menu: Bars3Icon,
  close: XMarkIcon,
  envelope: EnvelopeIcon,
  lifebuoy: LifebuoyIcon,
  clock: ClockIcon,
  document: DocumentTextIcon,
  academic: AcademicCapIcon,
  wrench: WrenchScrewdriverIcon,
  presentation: PresentationChartBarIcon,
  cog: Cog6ToothIcon,
  desktop: ComputerDesktopIcon,
  mobile: DevicePhoneMobileIcon,
  play: PlayIcon,
  'map-pin': MapPinIcon,
  trophy: TrophyIcon,
  newspaper: NewspaperIcon,
  beaker: BeakerIcon,
  'user-group': UserGroupIcon,
  ticket: TicketIcon,
  power: PowerIcon,
  head: UserCircleIcon,
  tongue: CursorArrowRaysIcon,
  sun: SunIcon,
  speaker: SpeakerWaveIcon,
  globe: GlobeAltIcon,
  building: BuildingLibraryIcon,
  star: StarIcon,
  quote: ChatBubbleBottomCenterTextIcon,
  'thumbs-up': HandThumbUpIcon,
  inbox: InboxIcon,
  megaphone: MegaphoneIcon,
  warning: ExclamationTriangleIcon,
  door: ArrowRightStartOnRectangleIcon,
  adjustments: AdjustmentsHorizontalIcon,
}
